from enum import Enum


class LocationName(Enum):
    YilanCounty = "宜蘭縣"
    HualienCounty = "花蓮縣"
    TaitungCounty = "臺東縣"
    PenghuCounty = "澎湖縣"
    KinmenCounty = "金門縣"
    LienchiangCounty = "連江縣"
    TaipeiCity = "臺北市"
    NewTaipeiCity = "新北市"
    TaoyuanCity = "桃園市"
    TaichungCity = "臺中市"
    TainanCity = "臺南市"
    KaohsiungCity = "高雄市"
    KeelungCity = "基隆市"
    HsinchuCounty = "新竹縣"
    HsinchuCity = "新竹市"
    MiaoliCounty = "苗栗縣"
    ChanghuaCounty = "彰化縣"
    NantouCounty = "南投縣"
    YunlinCounty = "雲林縣"
    ChiayiCounty = "嘉義縣"
    ChiayiCity = "嘉義市"
    PingtungCounty = "屏東縣"
